import { ArrowUpRight, Check, Compass, Layers3, MoveRight, ShieldCheck, SlidersHorizontal, Sparkles, Wrench, type LucideIcon } from "lucide-react";
import { Footer, Nav } from "./SiteChrome";

const services: [string, string, string, LucideIcon][] = [
  ["01", "Office Furniture Installation", "Assembly and placement of workstations, desks, chairs, and the pieces that make a workplace work.", Wrench],
  ["02", "Cubicle & Panel Systems", "Modular partitioning and privacy solutions that give every team room to focus and connect.", Layers3],
  ["03", "Office Relocations & Moves", "A complete move plan, careful handling, and precise reinstallation that keeps business moving.", MoveRight],
  ["04", "Ergonomic Workspace Solutions", "Health-focused workstation configuration for comfort, energy, and better everyday performance.", SlidersHorizontal],
  ["05", "Space Planning & Design", "Layouts optimized for productivity, flow, collaboration, and the way your people actually work.", Compass],
  ["06", "Technology Integration", "Cable management, power solutions, monitor arms, and the details behind a clean connected space.", Sparkles],
];

export default function Homepage() {
  return <main className="min-h-screen overflow-y-auto bg-[#fff] font-['Montserrat'] text-[#4E4B66]"><Nav/>
    <section id="home" className="relative flex min-h-[720px] items-end overflow-hidden bg-[#1A1A1A] pt-24"><img src="/__mockup/images/lwo-hero.png" alt="Modern commercial office architecture" className="absolute inset-0 h-full w-full object-cover opacity-65"/><div className="absolute inset-0 bg-gradient-to-r from-[#111]/95 via-[#111]/55 to-transparent"/><div className="relative mx-auto w-full max-w-7xl px-5 pb-24 lg:px-8 lg:pb-32"><p className="mb-7 text-xs font-bold uppercase tracking-[.25em] text-[#F46D0B]">Commercial office solutions / nationwide</p><h1 className="max-w-3xl text-5xl font-extrabold leading-[1.04] tracking-[-.045em] text-white md:text-7xl">The details of a better workplace, <span className="text-[#63c3be]">installed.</span></h1><p className="mt-8 max-w-xl text-base leading-8 text-white/70 md:text-lg">Lakewoods turns office plans into finished spaces — with expert furniture installation, workspace design, and a standard of care built for business.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#contact" className="flex items-center gap-3 bg-[#F46D0B] px-6 py-4 text-xs font-bold uppercase tracking-[.15em] text-white hover:bg-[#ff8530]">Start a project <ArrowUpRight size={17}/></a><a href="#services" className="flex items-center gap-3 border border-white/30 px-6 py-4 text-xs font-bold uppercase tracking-[.15em] text-white hover:border-white">Explore services <ArrowUpRight size={17}/></a></div></div><div className="absolute bottom-10 right-8 hidden text-right text-[10px] uppercase tracking-[.2em] text-white/45 lg:block">01 / 06<br/><span className="text-[#F46D0B]">Precision in motion</span></div></section>
    <section className="border-b border-[#dfe7e7] bg-[#f3f7f6]"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 md:grid-cols-3 lg:px-8"><div><p className="text-3xl font-extrabold text-[#1A1A1A]">25+</p><p className="mt-1 text-xs uppercase tracking-[.14em]">Years moving work forward</p></div><div><p className="text-3xl font-extrabold text-[#1A1A1A]">Nationwide</p><p className="mt-1 text-xs uppercase tracking-[.14em]">One partner, every location</p></div><div><p className="text-3xl font-extrabold text-[#1A1A1A]">White-glove</p><p className="mt-1 text-xs uppercase tracking-[.14em]">From first measure to final chair</p></div></div></section>
    <section id="services" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#1F8080]">What we do</p><h2 className="max-w-md text-4xl font-extrabold leading-tight tracking-[-.04em] text-[#1A1A1A] md:text-5xl">Your office is a system. We make it work as one.</h2><p className="mt-6 max-w-sm text-sm leading-7">From a single suite to a multi-site rollout, our commercial office solutions team brings planning, installation, and accountability under one roof.</p><a href="#contact" className="mt-9 inline-flex items-center gap-3 border-b-2 border-[#F46D0B] pb-3 text-xs font-bold uppercase tracking-[.15em] text-[#1A1A1A]">Talk to an expert <ArrowUpRight size={16}/></a></div><div className="grid gap-px bg-[#d7e2e1] sm:grid-cols-2">{services.map(([num, title, body, ServiceIcon]) => <article key={title} className="group bg-white p-7 transition-colors hover:bg-[#1F8080] hover:text-white"><div className="mb-10 flex items-start justify-between"><span className="text-xs font-bold text-[#F46D0B]">{num}</span><ServiceIcon size={22} strokeWidth={1.5} className="text-[#1F8080] group-hover:text-white"/></div><h3 className="max-w-xs text-lg font-bold leading-snug text-[#1A1A1A] group-hover:text-white">{title}</h3><p className="mt-3 text-sm leading-6 group-hover:text-white/70">{body}</p></article>)}</div></div></section>
    <section id="why-us" className="bg-[#1A1A1A] px-5 py-24 text-white lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1fr_1.1fr]"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#F46D0B]">The Lakewoods standard</p><h2 className="max-w-lg text-4xl font-extrabold leading-tight tracking-[-.04em] md:text-5xl">The right people in the room changes everything.</h2><p className="mt-6 max-w-lg text-sm leading-7 text-white/60">We are not a delivery drop-off. We are the partner who understands your schedule, protects your investment, and owns the last 10% that everyone remembers.</p></div><div className="grid gap-8 sm:grid-cols-2">{[["One accountable team","Planning, logistics, installation, and closeout aligned from day one."],["Built around your deadline","A clear schedule and proactive communication keep your opening on track."],["Craft over shortcuts","Every workstation is leveled, every cable considered, every room ready."],["Nationwide reach","Consistent execution for regional teams and national rollouts alike."]].map(([title, body]) => <div key={title} className="border-t border-white/20 pt-5"><Check className="mb-7 text-[#F46D0B]" size={20}/><h3 className="font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{body}</p></div>)}</div></div></section>
    <section id="about" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:py-32"><div className="relative min-h-[390px] overflow-hidden bg-[#d8e6e4]"><div className="absolute left-8 top-8 h-48 w-48 border border-[#1F8080]/40"/><div className="absolute bottom-0 right-0 h-64 w-3/4 bg-[#1F8080] p-8 text-white"><p className="text-5xl font-extrabold">01</p><p className="mt-2 max-w-[180px] text-xs uppercase leading-5 tracking-[.15em]">Partner for the whole workplace</p></div><div className="absolute left-16 top-20 h-48 w-2/3 bg-[#1A1A1A] shadow-2xl"><div className="h-full w-full bg-[linear-gradient(135deg,transparent_48%,#F46D0B_49%,#F46D0B_51%,transparent_52%)] opacity-80"/></div></div><div><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#1F8080]">A better handoff</p><h2 className="text-4xl font-extrabold leading-tight tracking-[-.04em] text-[#1A1A1A] md:text-5xl">Good work is felt before it is noticed.</h2><p className="mt-6 text-sm leading-7">Lakewoods Office Solutions helps organizations create spaces where people can do their best work. We pair a contractor's practical discipline with a designer's eye for how a room should feel.</p><div className="mt-8 flex items-center gap-4 border-t border-[#dfe7e7] pt-6"><ShieldCheck className="text-[#1F8080]" size={25}/><p className="text-xs font-semibold uppercase leading-5 tracking-[.1em] text-[#1A1A1A]">Trusted by facility teams, GCs, and growing companies</p></div></div></section>
    <section id="contact" className="bg-[#1F8080] px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 lg:flex-row lg:items-end"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#a6e1dd]">Let’s get to work</p><h2 className="max-w-2xl text-4xl font-extrabold leading-tight tracking-[-.04em] md:text-6xl">A sharper space starts with a sharper plan.</h2></div><a href="mailto:hello@lwosolutions.com" className="flex shrink-0 items-center gap-3 self-start bg-[#F46D0B] px-7 py-5 text-xs font-bold uppercase tracking-[.15em] hover:bg-[#ff8530] lg:self-end">Request a consultation <ArrowUpRight size={17}/></a></div></section>
    <Footer/>
  </main>;
}