import { ArrowUpRight, Check, Compass, Layers3, MoveRight, ShieldCheck, SlidersHorizontal, Sparkles, Wrench, type LucideIcon } from "lucide-react";
import { Footer, SectionMark, SiteHeader } from "./SiteChrome";

const services: [string, string, string, LucideIcon][] = [
  ["01", "OFFICE FURNITURE INSTALLATION", "Assembly and placement of workstations, desks, chairs, and the pieces that make a workplace work.", Wrench],
  ["02", "CUBICLE & PANEL SYSTEMS", "Modular partitioning and privacy solutions that give every team room to focus and connect.", Layers3],
  ["03", "OFFICE RELOCATIONS & MOVES", "A complete move plan, careful handling, and precise reinstallation that keeps business moving.", MoveRight],
  ["04", "ERGONOMIC WORKSPACE SOLUTIONS", "Health-focused workstation configuration for comfort, energy, and better everyday performance.", SlidersHorizontal],
  ["05", "SPACE PLANNING & DESIGN", "Layouts optimized for productivity, flow, collaboration, and the way your people actually work.", Compass],
  ["06", "TECHNOLOGY INTEGRATION", "Cable management, power solutions, monitor arms, and the details behind a clean connected space.", Sparkles],
];

export default function Homepage() {
  return <main className="min-h-screen overflow-y-auto bg-white font-['Montserrat'] text-[#4E4B66]"><SiteHeader />
    <section className="mx-auto max-w-4xl px-5 py-16 text-center md:py-24"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#1F8080]">LAKEWOODS OFFICE SOLUTIONS</p><h1 className="mt-6 text-3xl font-bold uppercase leading-[1.25] tracking-[.18em] text-[#1A1A1A] md:text-5xl">Transforming offices.<br/><span className="text-[#1F8080]">Elevating work.</span></h1><p className="mx-auto mt-8 max-w-2xl text-sm leading-8">We provide complete commercial office solutions for businesses nationwide — from office furniture installation and cubicle systems to workplace design, relocation, and ergonomic planning.</p><a href="#contact" className="mt-9 inline-flex items-center gap-3 bg-[#F46D0B] px-7 py-4 text-[10px] font-bold uppercase tracking-[.2em] text-white hover:bg-[#d95d07]">CALL NOW <ArrowUpRight size={15}/></a></section>
    <SectionMark />
    <section id="services" className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="mb-12 text-center"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#1F8080]">OFFICE INSTALLATIONS SERVICES</p><h2 className="mt-5 text-3xl font-bold uppercase tracking-[.16em] text-[#1A1A1A] md:text-4xl">Built around how you work</h2></div><div className="grid gap-px border border-[#d8d0c3] bg-[#d8d0c3] md:grid-cols-2 lg:grid-cols-3">{services.map(([num,title,body,Icon]) => <article key={title} className="bg-white p-8 transition-colors hover:bg-[#fbfaf7]"><div className="flex items-center justify-between"><span className="text-xs font-bold tracking-[.2em] text-[#C9A96E]">{num}</span><Icon size={22} strokeWidth={1.3} className="text-[#1F8080]"/></div><h3 className="mt-10 text-sm font-bold uppercase leading-6 tracking-[.12em] text-[#1F8080]">{title}</h3><p className="mt-4 text-sm leading-7">{body}</p></article>)}</div></section>
    <section id="why-us" className="border-y border-[#d8d0c3] bg-white px-5 py-20"><div className="mx-auto max-w-6xl text-center"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#1F8080]">WHY LAKEWOODS</p><h2 className="mt-5 text-3xl font-bold uppercase tracking-[.16em] text-[#1A1A1A]">Precision is our promise</h2><p className="mx-auto mt-7 max-w-2xl text-sm leading-8">From first measure to final chair, our team brings thoughtful planning, clear communication, and white-glove execution to every commercial workspace.</p><div className="mt-12 grid gap-8 text-left md:grid-cols-3">{[["25+", "Years of experience"],["NATIONWIDE", "Consistent project delivery"],["ONE TEAM", "Planning through closeout"]].map(([large,small]) => <div key={large} className="border-t-2 border-[#C9A96E] pt-5"><p className="text-3xl font-bold tracking-[.1em] text-[#1A1A1A]">{large}</p><p className="mt-3 text-xs uppercase tracking-[.17em] text-[#1F8080]">{small}</p></div>)}</div></div></section>
    <SectionMark />
    <section id="about" className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div className="relative min-h-[340px] overflow-hidden bg-[#1A1A1A]"><img src="/__mockup/images/lwo-installation.png" alt="Office furniture installation" className="h-full w-full object-cover opacity-75"/><div className="absolute bottom-0 left-0 border-t border-[#C9A96E] bg-[#1A1A1A]/90 px-7 py-5 text-[10px] font-bold uppercase tracking-[.2em] text-[#C9A96E]">The Lakewoods standard</div></div><div className="flex flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#1F8080]">THE DIFFERENCE IS IN THE DETAILS</p><h2 className="mt-5 text-3xl font-bold uppercase leading-[1.3] tracking-[.13em] text-[#1A1A1A]">Your workplace,<br/>done right.</h2><p className="mt-7 text-sm leading-8">Lakewoods Office Solutions is the trusted partner for organizations that expect more from their office installation and workspace design. We protect your investment, your timeline, and your people’s experience.</p><div className="mt-8 flex gap-3 text-xs font-bold uppercase tracking-[.12em] text-[#1F8080]"><ShieldCheck size={20}/> ACCOUNTABLE FROM PLAN TO HANDOFF</div></div></section>
    <section id="contact" className="border-t border-[#d8d0c3] px-5 py-20 text-center"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#1F8080]">READY TO GET STARTED?</p><h2 className="mx-auto mt-5 max-w-3xl text-3xl font-bold uppercase leading-[1.35] tracking-[.15em] text-[#1A1A1A] md:text-4xl">Let’s create a space that works harder.</h2><a href="mailto:hello@lwosolutions.com" className="mt-9 inline-flex items-center gap-3 bg-[#F46D0B] px-7 py-4 text-[10px] font-bold uppercase tracking-[.2em] text-white hover:bg-[#d95d07]">REQUEST A CONSULTATION <ArrowUpRight size={15}/></a></section><Footer />
  </main>;
}