import { ArrowUpRight, ChevronDown, CheckCircle2, ClipboardCheck, DraftingCompass, Truck, type LucideIcon } from "lucide-react";
import { useState } from "react";
import { Footer, Nav } from "./SiteChrome";

const faqs = [
  ["What does your office furniture installation service include?", "Our team handles receiving, inventory, assembly, placement, leveling, punch-list corrections, and removal of packaging. We can coordinate directly with your furniture dealer or general contractor."],
  ["Can you install furniture purchased from another vendor?", "Yes. We regularly install dealer-supplied and client-supplied systems. Before we begin, we confirm specifications, site readiness, and the installation sequence."],
  ["How far in advance should we schedule?", "Most projects are best scheduled four to six weeks ahead. For urgent openings or phased rollouts, contact us early and we will build the most practical plan around your date."],
  ["Do you support multi-location rollouts?", "Absolutely. Our nationwide network and centralized project communication keep standards consistent across offices, cities, and time zones."],
];
const process: [string, string, string, LucideIcon][] = [["01","Scope","We review plans, furniture specs, access, and the date that matters.", DraftingCompass],["02","Coordinate","Your project lead aligns deliveries, trades, and site readiness.",ClipboardCheck],["03","Install","Our team assembles, places, levels, and protects every piece.",Truck],["04","Handoff","We walk the space, resolve the details, and leave it ready.",CheckCircle2]];
export default function ServicePage() {
  const [active, setActive] = useState<number | null>(0);
  return <main className="min-h-screen overflow-y-auto bg-white font-['Montserrat'] text-[#4E4B66]"><Nav/>
    <section className="relative overflow-hidden bg-[#1A1A1A] pt-32 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8 lg:pb-28"><div><p className="mb-7 text-xs font-bold uppercase tracking-[.22em] text-[#F46D0B]">Service / 01</p><h1 className="max-w-xl text-5xl font-extrabold leading-[1.04] tracking-[-.05em] md:text-7xl">Office Furniture <span className="text-[#63c3be]">Installation</span></h1><p className="mt-8 max-w-lg text-base leading-8 text-white/65">From first delivery to final alignment, we make sure your furniture arrives, assembles, and performs exactly as planned.</p><a href="#contact" className="mt-9 inline-flex items-center gap-3 bg-[#F46D0B] px-6 py-4 text-xs font-bold uppercase tracking-[.15em] hover:bg-[#ff8530]">Plan your installation <ArrowUpRight size={17}/></a></div><div className="relative h-[390px] overflow-hidden"><img src="/__mockup/images/lwo-installation.png" alt="Professionals installing modern office furniture" className="h-full w-full object-cover"/><div className="absolute inset-0 border-[14px] border-[#1A1A1A]/40"/><span className="absolute bottom-6 left-6 bg-[#1F8080] px-4 py-3 text-[10px] font-bold uppercase tracking-[.16em]">Precision at every station</span></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-[1fr_.8fr] lg:px-8 lg:py-32"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#1F8080]">Installation without interruption</p><h2 className="max-w-2xl text-4xl font-extrabold leading-tight tracking-[-.04em] text-[#1A1A1A] md:text-5xl">Your furniture should be ready when your people are.</h2><p className="mt-7 max-w-2xl text-sm leading-7">Office furniture installation is more than putting pieces together. It is the final expression of your space plan — and a critical moment for your schedule, budget, and employee experience. Lakewoods coordinates the moving parts and leaves you with a workplace that is level, clean, and ready.</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{["Dealer and client-supplied furniture","Workstations, desks, and conference rooms","Inventory, assembly, and placement","Punch-list and closeout support"].map(item => <div key={item} className="flex items-start gap-3 border-t border-[#dfe7e7] pt-4 text-sm font-semibold text-[#1A1A1A]"><CheckCircle2 size={18} className="shrink-0 text-[#1F8080]"/>{item}</div>)}</div></div><div className="bg-[#f3f7f6] p-8 lg:p-10"><p className="text-6xl font-extrabold text-[#F46D0B]">01</p><p className="mt-10 text-xs font-bold uppercase tracking-[.18em] text-[#1A1A1A]">One partner, zero guesswork</p><p className="mt-4 text-sm leading-7">A dedicated project lead keeps your dealer, facilities team, installers, and deadline moving in the same direction.</p></div></section>
    <section className="bg-[#f3f7f6] px-5 py-24 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#1F8080]">How it works</p><h2 className="text-4xl font-extrabold tracking-[-.04em] text-[#1A1A1A] md:text-5xl">A clear path to a finished room.</h2><div className="mt-14 grid gap-px bg-[#d4e0de] md:grid-cols-4">{process.map(([num,title,body,Icon]) => <div key={title} className="bg-white p-7"><Icon size={24} className="text-[#1F8080]"/><p className="mt-10 text-xs font-bold text-[#F46D0B]">{num}</p><h3 className="mt-2 text-xl font-bold text-[#1A1A1A]">{title}</h3><p className="mt-3 text-sm leading-6">{body}</p></div>)}</div></div></section>
    <section className="mx-auto grid max-w-5xl gap-12 px-5 py-24 lg:grid-cols-[.7fr_1.3fr] lg:px-8"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#1F8080]">Questions, answered</p><h2 className="text-4xl font-extrabold leading-tight tracking-[-.04em] text-[#1A1A1A]">Before the first box arrives.</h2></div><div>{faqs.map(([question, answer], index) => <div key={question} className="border-t border-[#dfe7e7]"><button onClick={() => setActive(active === index ? null : index)} className="flex w-full items-center justify-between py-6 text-left text-sm font-bold text-[#1A1A1A]">{question}<ChevronDown size={18} className={`text-[#1F8080] transition-transform ${active === index ? "rotate-180" : ""}`}/></button>{active === index && <p className="pb-6 pr-8 text-sm leading-7">{answer}</p>}</div>)}</div></section>
    <section className="bg-[#1A1A1A] px-5 py-24 text-white lg:px-8"><div className="mx-auto max-w-7xl"><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#F46D0B]">Keep building</p><div className="flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><h2 className="max-w-2xl text-4xl font-extrabold leading-tight tracking-[-.04em] md:text-5xl">Installation is one part of the bigger picture.</h2><a href="#contact" className="flex shrink-0 items-center gap-3 border border-white/30 px-6 py-4 text-xs font-bold uppercase tracking-[.15em] hover:border-white">View related services <ArrowUpRight size={17}/></a></div><div className="mt-14 grid gap-4 md:grid-cols-3">{["Cubicle & Panel Systems","Office Relocations & Moves","Ergonomic Workspace Solutions"].map((title,i) => <a href="#contact" key={title} className="group border border-white/15 p-7 hover:border-[#F46D0B]"><p className="text-xs font-bold text-[#F46D0B]">0{i+2}</p><h3 className="mt-14 text-lg font-bold">{title}</h3><span className="mt-8 inline-flex items-center gap-2 text-xs uppercase tracking-[.15em] text-white/55 group-hover:text-white">Explore <ArrowUpRight size={15}/></span></a>)}</div></div></section>
    <section id="contact" className="bg-[#1F8080] px-5 py-20 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a6e1dd]">Ready when you are</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.04em] md:text-5xl">Let’s get your installation on the calendar.</h2></div><a href="mailto:hello@lwosolutions.com" className="flex shrink-0 items-center gap-3 bg-[#F46D0B] px-7 py-5 text-xs font-bold uppercase tracking-[.15em] hover:bg-[#ff8530]">Request a consultation <ArrowUpRight size={17}/></a></div></section><Footer/>
  </main>;
}