// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lwo-website/DesignPage.tsx": () => import("../components/mockups/lwo-website/DesignPage.tsx"),
  "./components/mockups/lwo-website/Homepage.tsx": () => import("../components/mockups/lwo-website/Homepage.tsx"),
  "./components/mockups/lwo-website/MovingPage.tsx": () => import("../components/mockups/lwo-website/MovingPage.tsx"),
  "./components/mockups/lwo-website/PaintingPage.tsx": () => import("../components/mockups/lwo-website/PaintingPage.tsx"),
  "./components/mockups/lwo-website/RelocationPage.tsx": () => import("../components/mockups/lwo-website/RelocationPage.tsx"),
  "./components/mockups/lwo-website/ServicePage.tsx": () => import("../components/mockups/lwo-website/ServicePage.tsx"),
  "./components/mockups/lwo-website/ServiceTemplate.tsx": () => import("../components/mockups/lwo-website/ServiceTemplate.tsx"),
  "./components/mockups/lwo-website/SiteChrome.tsx": () => import("../components/mockups/lwo-website/SiteChrome.tsx"),
  "./components/mockups/lwo-website/StoragePage.tsx": () => import("../components/mockups/lwo-website/StoragePage.tsx")
};
