// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lwo-website/Homepage.tsx": () => import("../components/mockups/lwo-website/Homepage.tsx"),
  "./components/mockups/lwo-website/ServicePage.tsx": () => import("../components/mockups/lwo-website/ServicePage.tsx"),
  "./components/mockups/lwo-website/SiteChrome.tsx": () => import("../components/mockups/lwo-website/SiteChrome.tsx")
};
